name: pocket-js-server

services:
  pg:
    image: bitnami/postgresql:15.8.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit
  